export const USER_LOGIN = "USER_LOGIN";
export const FETCH_HEADLINE_DATA_SUCCESS = 'FETCH_HEADLINE_DATA_SUCCESS';
export const FETCH_HEADLINE_DATA_FAILURE = 'FETCH_HEADLINE_DATA_FAILURE';
export const FETCH_HEADLINE_IMAGE_SUCCESS = 'FETCH_HEADLINE_IMAGE_SUCCESS';
export const FETCH_HEADLINE_IMAGE_FAILURE = 'FETCH_HEADLINE_IMAGE_FAILURE';
export const ADD_MEMBER_DATA_SUCCESS = 'ADD_MEMBER_DATA_SUCCESS';
export const ADD_MEMBER_DATA_FAILURE = 'ADD_MEMBER_DATA_FAILURE';